name = "CircularArrays"
uuid = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
license = "MIT"
desc = "Arrays with fixed size and circular indexing."
authors = ["Vexatos <Stuarzt@gmx.de>"]
url = "https://github.com/Vexatos/CircularArrays.jl"
version = "1.0.0"

[compat]
julia = "1.3"
