name = "CircularArrays"
uuid = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
license = "MIT"
desc = "Arrays with fixed size and circular indexing."
authors = ["Vexatos <Stuarzt@gmx.de>"]
url = "https://github.com/Vexatos/CircularArrays.jl"
version = "1.1.0"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
OffsetArrays = "1.0.2"
julia = "1.3"
